//main.cpp

//

// DO NOT EDIT THIS FILE

// WRITE YOUR CODE IN IntegerLinkedList.h and IntegerLinkedList.cpp

//

#include <iostream>

#include <string>

#include "IntegerLinkedList.h"

using namespace std;

int main() {

IntegerLinkedList mylist;

cout << "Enter number of integers : ";

int n, value;

cin >> n;

cout << "Enter " << n << " integers" << endl;

for (int i = 0; i < n; i++) {

cin >> value;

mylist.addFront(value);

}

cout << "print: " << endl;

mylist.print();

cout << endl;

mylist.deleteSmallest();

cout << "print after deleteSmallest: " << mylist.print() << endl;

}

/*output1:

Enter number of integers : 5

Enter 5 integers

10

5

4

7

1

print:

1 7 4 5 10

7 4 5 10

print after deleteSmallest: 7 4 5 10

output2:

Enter number of integers : 10

Enter 10 integers

1

6

19

10

2

34

11

15

11

19

print:

19 11 15 11 34 2 10 19 6 1

19 11 15 11 34 2 10 19 6

print after deleteSmallest: 19 11 15 11 34 2 10 19 6

output3:

Enter number of integers : 5

Enter 5 integers

3

10

2

18

10

print:

10 18 2 10 3

10 18 10 3

print after deleteSmallest: 10 18 10 3

*/
